replicaCount: 2

image:
  repository: ghcr.io/mikhael-remboski/nodejs-backend-template
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: nodejs-backend-template.microservices.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
          port: 8080
  tls:
    - secretName: nodejs-backend-template-tls
      hosts:
        - nodejs-backend-template.microservices.example.com

resources:
  limits:
    cpu: "100m"
    memory: "128Mi"
  requests:
    cpu: "50m"
    memory: "128Mi"

nodeSelector: { }

tolerations: [ ]

affinity: { }
